#!/usr/bin/env bash
# Generate + apply the rdq-research resource-caps drop-in, sized to the
# CURRENT hardware. Owns ~/.config/systemd/user/rdq-research.service.d/
# resources.conf (previously hand-written, 2026-08-05): run this once after
# any droplet resize (ops/resize_research.sh does it for you) and the caps
# scale to the new core/memory envelope instead of pinning the box to the
# 4-core / 8G numbers.
#
# Sizing rules (integer GiB, memory rounded to nearest — an "8 GB" droplet
# reports ~7.8Gi):
#   threads    = max(3, cores - 2)     BLAS/OMP caps, host AND container.
#                docker-py's cpu_count kwarg is Windows-only, so these thread
#                caps ARE the effective CPU limit for qlib containers.
#   docker mem = max(4, mem - 4) GiB   qlib training container hard limit.
#   shm        = max(2, docker_mem/2)
#   MemoryHigh = max(3, mem/4)         host-side venv work (server_ui +
#                                      factor CoSTEER), not the containers.
#   CPUWeight  = 40 below 8 cores (protect the orchestrator/monitoring on a
#                small shared box), 80 at 8+ (dedicated cores; contention is
#                no longer the failure mode).
#
# The qrun wall-clock stays at rdagent's 3600s default ON PURPOSE — the loop
# adapts model size to the budget (2026-08-05 us_liquid run); more cores make
# the budget generous instead of binding.
#
# Usage:
#   ops/research_caps.sh              # write drop-in, daemon-reload, restart
#   ops/research_caps.sh --print      # emit generated conf to stdout only
#   ops/research_caps.sh --no-restart # write drop-in only (no systemd calls)
#   ops/research_caps.sh --force      # restart even if a run looks active
#
# Overrides (tests / dry-runs): RDQ_CAPS_CORES, RDQ_CAPS_MEM_GB, RDQ_CAPS_FILE.
set -euo pipefail

PRINT_ONLY=0
NO_RESTART=0
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --print) PRINT_ONLY=1 ;;
    --no-restart) NO_RESTART=1 ;;
    --force) FORCE=1 ;;
    *) echo "ERROR: unknown argument: $arg" >&2; exit 2 ;;
  esac
done

CORES="${RDQ_CAPS_CORES:-$(nproc)}"
if [[ -n "${RDQ_CAPS_MEM_GB:-}" ]]; then
  MEM_GB="$RDQ_CAPS_MEM_GB"
else
  mem_kb="$(awk '/^MemTotal:/ {print $2}' /proc/meminfo)"
  MEM_GB=$(( (mem_kb + 524288) / 1048576 ))
fi

THREADS=$(( CORES - 2 )); (( THREADS < 3 )) && THREADS=3
DOCKER_MEM_GB=$(( MEM_GB - 4 )); (( DOCKER_MEM_GB < 4 )) && DOCKER_MEM_GB=4
SHM_GB=$(( DOCKER_MEM_GB / 2 )); (( SHM_GB < 2 )) && SHM_GB=2
MEMHIGH_GB=$(( MEM_GB / 4 )); (( MEMHIGH_GB < 3 )) && MEMHIGH_GB=3
if (( CORES < 8 )); then CPUWEIGHT=40; else CPUWEIGHT=80; fi

CAPS_FILE="${RDQ_CAPS_FILE:-$HOME/.config/systemd/user/rdq-research.service.d/resources.conf}"

generate() {
  cat <<EOF
# GENERATED by ops/research_caps.sh for ${CORES} cores / ${MEM_GB}G — do not
# hand-edit; rerun the script (it re-detects hardware) after any resize.
#
# Two enforcement layers because the work splits across host and containers:
# 1. Host side (server_ui + factor CoSTEER code in the repo venv): systemd
#    cgroup weights + BLAS/OMP thread caps on the service env.
# 2. Container side (qlib backtests / model training in local_qlib:latest):
#    docker mem_limit via QLIB_DOCKER_MEM_LIMIT, and thread caps injected via
#    QLIB_DOCKER_ENV_DICT — docker-py's cpu_count is Windows-only, so the
#    thread caps ARE the effective CPU limit; systemd CPUWeight does NOT
#    cover containers (dockerd's cgroup, not the service's).
#
# QLIB_DOCKER_ENV_DICT here REPLACES the unit's value — it must keep
# MLFLOW_ALLOW_FILE_STORE, or every backtest dies in create_exp.
[Service]
CPUWeight=${CPUWEIGHT}
MemoryHigh=${MEMHIGH_GB}G
Environment="OMP_NUM_THREADS=${THREADS}" "MKL_NUM_THREADS=${THREADS}" "OPENBLAS_NUM_THREADS=${THREADS}" "NUMEXPR_NUM_THREADS=${THREADS}"
Environment="QLIB_DOCKER_MEM_LIMIT=${DOCKER_MEM_GB}g"
Environment="QLIB_DOCKER_SHM_SIZE=${SHM_GB}g"
Environment="QLIB_DOCKER_ENV_DICT={\\"MLFLOW_ALLOW_FILE_STORE\\":\\"true\\",\\"OMP_NUM_THREADS\\":\\"${THREADS}\\",\\"MKL_NUM_THREADS\\":\\"${THREADS}\\",\\"OPENBLAS_NUM_THREADS\\":\\"${THREADS}\\",\\"NUMEXPR_NUM_THREADS\\":\\"${THREADS}\\"}"
EOF
}

if (( PRINT_ONLY )); then
  generate
  exit 0
fi

mkdir -p "$(dirname "$CAPS_FILE")"
NEW_CONTENT="$(generate)"
if [[ -f "$CAPS_FILE" ]] && [[ "$(cat "$CAPS_FILE")" == "$NEW_CONTENT" ]]; then
  echo "caps unchanged (${CORES} cores / ${MEM_GB}G): $CAPS_FILE"
  exit 0
fi
printf '%s\n' "$NEW_CONTENT" > "$CAPS_FILE"
echo "wrote $CAPS_FILE (${CORES} cores / ${MEM_GB}G -> threads=${THREADS}, docker mem=${DOCKER_MEM_GB}g, shm=${SHM_GB}g, MemoryHigh=${MEMHIGH_GB}G, CPUWeight=${CPUWEIGHT})"

if (( NO_RESTART )); then
  echo "skipping daemon-reload/restart (--no-restart); apply later with:"
  echo "  systemctl --user daemon-reload && systemctl --user restart rdq-research.service"
  exit 0
fi

# Restarting rdq-research kills any research loop it spawned. Backtests show
# up as local_qlib containers; loop phases between backtests show up as
# fin_quant processes.
active=""
active+="$(docker ps -q --filter ancestor=local_qlib:latest 2>/dev/null || true)"
active+="$(pgrep -u "$(id -un)" -f fin_quant 2>/dev/null || true)"
if [[ -n "$active" ]] && (( ! FORCE )); then
  echo "ERROR: a research run looks active (local_qlib container or fin_quant" >&2
  echo "process). Restarting rdq-research would kill it. Re-run with --force" >&2
  echo "to restart anyway, or wait for the run to finish." >&2
  exit 1
fi

export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
systemctl --user daemon-reload
systemctl --user restart rdq-research.service
echo "rdq-research restarted with new caps"
