#!/usr/bin/env bash
# ops/run_us_quant.sh — US-market RD-Agent(Q) fin_quant run wrapper (US-017).
#
# Usage:
#   ops/run_us_quant.sh --check                            # validate everything, no launch
#   ops/run_us_quant.sh [--loop_n N] [--all_duration DUR]  # launch (default --loop_n 1)
#
# Default mode wraps:
#   onecli run --agent rdq-research -- rdagent fin_quant --loop_n 1
# with the US-market environment exported (wire_env):
#   - Dates: TRAIN/VALID/TEST segments exported under ALL THREE prefixes
#     QLIB_QUANT_ / QLIB_FACTOR_ / QLIB_MODEL_. The quant scenario prompt reads
#     QLIB_QUANT_*, but the runners re-instantiate FactorBasePropSetting() /
#     ModelBasePropSetting() and render the workspace conf jinja vars from
#     QLIB_FACTOR_* / QLIB_MODEL_* (rdagent developer/{factor,model}_runner.py)
#     — setting only QLIB_QUANT_* would silently backtest on the CN defaults.
#     Override via RDQ_TRAIN_START, RDQ_TRAIN_END, RDQ_VALID_START,
#     RDQ_VALID_END, RDQ_TEST_START, RDQ_TEST_END.
#   - Factor source: FACTOR_CoSTEER_DATA_FOLDER(_DEBUG) -> the data_folder/ and
#     data_folder_debug/ dirs generated by data/make_factor_source.py
#     (default root ~/rdq-data/factor_source/us_liquid; override RDQ_FACTOR_SOURCE).
#   - Prompts: APP_TPL -> research/app_tpl (US wording overrides, US-016).
#   - Workspace templates: QLIB_QUANT_FACTOR_HYPOTHESIS2EXPERIMENT /
#     QLIB_QUANT_MODEL_HYPOTHESIS2EXPERIMENT -> research.us_quant.US* subclasses
#     that re-inject research/us_templates (APP_TPL cannot redirect the
#     hardcoded workspace template folders; see research/us_quant.py).
#   - LOG_TRACE_PATH (timestamped) / WORKSPACE_PATH under ~/rdq-runs/us_quant/
#     (override root with RDQ_RUN_ROOT, or either var directly).
#
# Universe: us_liquid — pinned inside the template YAMLs (market: us_liquid,
# benchmark: SPY). Per-run custom universes are US-023's job. The us_data store
# (~/.qlib/qlib_data/us_data, hardcoded as provider_uri in the templates) MUST
# contain SPY. RDQ_QLIB_STORE overrides the path --check inspects — that
# override exists for tests only; the launched run always uses the
# provider_uri baked into the templates.
#
# FULL-RUN COMPLETION CRITERION (declare a run good only when all hold):
#   - qlib_res.csv in the run workspace with a non-NaN IC
#   - |ARR| < 200% (annualized return not absurd) and MDD < 0
#     (max drawdown reported negative, i.e. a real backtest ran)
#   - mlruns/**/pred.pkl in the workspace indexed by US tickers
#     (AAPL/MSFT/..., not SH600xxx)
# First full run builds the local_qlib:latest docker image if missing (slow —
# budget an hour+); later runs reuse it.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="${REPO_ROOT}/.venv"
RDAGENT="${VENV}/bin/rdagent"
PYTHON="${VENV}/bin/python"
ONECLI_URL="${ONECLI_URL:-http://127.0.0.1:10254}"

RUN_ROOT="${RDQ_RUN_ROOT:-${HOME}/rdq-runs/us_quant}"
STORE="${RDQ_QLIB_STORE:-${HOME}/.qlib/qlib_data/us_data}"
FACTOR_SOURCE="${RDQ_FACTOR_SOURCE:-${HOME}/rdq-data/factor_source/us_liquid}"
UNIVERSE="us_liquid"

usage() {
  sed -n '2,47p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

wire_env() {
  # Dates — one RDQ_* knob fans out to the three rdagent settings prefixes.
  local train_start="${RDQ_TRAIN_START:-2016-01-01}"
  local train_end="${RDQ_TRAIN_END:-2022-12-31}"
  local valid_start="${RDQ_VALID_START:-2023-01-01}"
  local valid_end="${RDQ_VALID_END:-2024-12-31}"
  local test_start="${RDQ_TEST_START:-2025-01-01}"
  local test_end="${RDQ_TEST_END:-2026-07-10}"

  local prefix
  for prefix in QLIB_QUANT QLIB_FACTOR QLIB_MODEL; do
    export "${prefix}_TRAIN_START=${train_start}"
    export "${prefix}_TRAIN_END=${train_end}"
    export "${prefix}_VALID_START=${valid_start}"
    export "${prefix}_VALID_END=${valid_end}"
    export "${prefix}_TEST_START=${test_start}"
    export "${prefix}_TEST_END=${test_end}"
  done

  export FACTOR_CoSTEER_DATA_FOLDER="${FACTOR_SOURCE}/data_folder"
  export FACTOR_CoSTEER_DATA_FOLDER_DEBUG="${FACTOR_SOURCE}/data_folder_debug"
  # Execution environments (US-043, mirror rdq-research.service): docker for
  # qlib backtests/model training (no conda on this box), the repo venv's
  # interpreter for generated factor code.
  export MODEL_CoSTEER_ENV_TYPE="docker"
  export FACTOR_CoSTEER_PYTHON_BIN="${PYTHON}"
  # Ops owns local_qlib:latest — in-run prepare() would rebuild it with
  # docker-py's legacy builder every time (no BuildKit cache, ~1h).
  export QLIB_DOCKER_BUILD_FROM_DOCKERFILE="false"
  # MLflow >= 3.6 in the image refuses the ./mlruns file store that qlib's
  # recorder is hardwired to; without this every backtest dies in create_exp.
  export QLIB_DOCKER_ENV_DICT='{"MLFLOW_ALLOW_FILE_STORE":"true"}'
  # LiteLLM rejects temperature!=1 for Claude models; rdagent sends 0.5.
  export LITELLM_DROP_PARAMS="true"
  export APP_TPL="${REPO_ROOT}/research/app_tpl"
  export QLIB_QUANT_FACTOR_HYPOTHESIS2EXPERIMENT="research.us_quant.USQlibFactorHypothesis2Experiment"
  export QLIB_QUANT_MODEL_HYPOTHESIS2EXPERIMENT="research.us_quant.USQlibModelHypothesis2Experiment"
}

check_dates() {
  # ISO dates compare correctly as strings.
  local ok=1
  [[ "${QLIB_QUANT_TRAIN_START}" < "${QLIB_QUANT_TRAIN_END}" ]] || ok=0
  [[ "${QLIB_QUANT_TRAIN_END}" < "${QLIB_QUANT_VALID_START}" ]] || ok=0
  [[ "${QLIB_QUANT_VALID_START}" < "${QLIB_QUANT_VALID_END}" ]] || ok=0
  [[ "${QLIB_QUANT_VALID_END}" < "${QLIB_QUANT_TEST_START}" ]] || ok=0
  [[ "${QLIB_QUANT_TEST_START}" < "${QLIB_QUANT_TEST_END}" ]] || ok=0
  [[ ${ok} -eq 1 ]] || fail "date segments not strictly ordered: train ${QLIB_QUANT_TRAIN_START}..${QLIB_QUANT_TRAIN_END} valid ${QLIB_QUANT_VALID_START}..${QLIB_QUANT_VALID_END} test ${QLIB_QUANT_TEST_START}..${QLIB_QUANT_TEST_END}"
  echo "PASS: dates ordered (train ${QLIB_QUANT_TRAIN_START}..${QLIB_QUANT_TRAIN_END}, valid ..${QLIB_QUANT_VALID_END}, test ..${QLIB_QUANT_TEST_END})"
}

require_file() {
  [[ -f "$1" ]] || fail "$2: missing file $1"
}

require_dir() {
  [[ -d "$1" ]] || fail "$2: missing directory $1"
}

check_mode() {
  wire_env
  check_dates

  [[ -x "${RDAGENT}" ]] || fail "rdagent not installed at ${RDAGENT} (run research/install.sh)"
  [[ -x "${PYTHON}" ]] || fail "venv python missing at ${PYTHON}"
  require_file "${REPO_ROOT}/research/.env" "LLM env (copy research/.env.example)"
  echo "PASS: rdagent + research/.env present"

  # Qlib US store (provider_uri baked into the templates).
  require_dir "${STORE}" "us_data store (build with data/build_store.py)"
  require_file "${STORE}/calendars/day.txt" "us_data store calendar"
  require_file "${STORE}/instruments/all.txt" "us_data store instruments"
  require_file "${STORE}/instruments/${UNIVERSE}.txt" \
    "universe (create with: python -m data.make_universe --name ${UNIVERSE})"
  grep -q "^SPY	" "${STORE}/instruments/all.txt" \
    || fail "benchmark SPY not in ${STORE}/instruments/all.txt (rebuild the store including SPY)"
  echo "PASS: us_data store + ${UNIVERSE} universe + SPY benchmark"

  # Factor coder source data (US-015 output).
  local f
  for f in "${FACTOR_CoSTEER_DATA_FOLDER}/daily_pv.h5" \
           "${FACTOR_CoSTEER_DATA_FOLDER}/README.md" \
           "${FACTOR_CoSTEER_DATA_FOLDER_DEBUG}/daily_pv.h5" \
           "${FACTOR_CoSTEER_DATA_FOLDER_DEBUG}/README.md"; do
    require_file "${f}" \
      "factor source (generate with: python -m data.make_factor_source --universe ${UNIVERSE} --output ${FACTOR_SOURCE})"
  done
  echo "PASS: FACTOR_CoSTEER_DATA_FOLDER(_DEBUG) populated"

  # Prompt overrides + US workspace templates.
  require_file "${APP_TPL}/scenarios/qlib/experiment/prompts.yaml" "APP_TPL override"
  require_file "${APP_TPL}/scenarios/qlib/factor_experiment_loader/prompts.yaml" "APP_TPL override"
  for f in factor_template/conf_baseline.yaml \
           factor_template/conf_combined_factors.yaml \
           factor_template/conf_combined_factors_sota_model.yaml \
           factor_template/read_exp_res.py \
           model_template/conf_baseline_factors_model.yaml \
           model_template/conf_sota_factors_model.yaml \
           model_template/read_exp_res.py; do
    require_file "${REPO_ROOT}/research/us_templates/${f}" "US template"
  done
  echo "PASS: APP_TPL overrides + US templates present"

  # The class paths the QLIB_QUANT_* env vars point at must import.
  "${PYTHON}" - <<'PY' || fail "US hypothesis2experiment classes failed to import (see research/us_quant.py)"
import os
from rdagent.core.utils import import_class
for var in (
    "QLIB_QUANT_FACTOR_HYPOTHESIS2EXPERIMENT",
    "QLIB_QUANT_MODEL_HYPOTHESIS2EXPERIMENT",
):
    import_class(os.environ[var])
PY
  echo "PASS: research.us_quant hook classes import"

  docker info >/dev/null 2>&1 || fail "docker is not usable without sudo (add user to the docker group)"
  echo "PASS: docker reachable sudo-less"

  command -v onecli >/dev/null 2>&1 || fail "onecli CLI not found on PATH"
  curl -fsS "${ONECLI_URL}/api/health" >/dev/null 2>&1 \
    || curl -fsS "${ONECLI_URL}/" >/dev/null 2>&1 \
    || fail "OneCLI gateway not reachable at ${ONECLI_URL}"
  onecli agents list 2>/dev/null | jq -e \
    '.data[] | select(.identifier == "rdq-research")' >/dev/null \
    || fail "identity rdq-research not registered (run ops/setup_onecli.sh)"
  echo "PASS: onecli gateway up, rdq-research registered"

  echo "OK: environment ready for a US fin_quant run (rerun without --check to launch)"
}

run_mode() {
  local loop_n="$1"
  local all_duration="$2"

  [[ -x "${RDAGENT}" ]] || fail "rdagent not installed at ${RDAGENT} (run research/install.sh)"

  local env_file="${REPO_ROOT}/research/.env"
  [[ -f "${env_file}" ]] || fail "missing ${env_file} (copy research/.env.example and keep placeholder keys)"
  set -a
  # shellcheck disable=SC1090
  source "${env_file}"
  set +a

  wire_env
  check_dates

  local ts
  ts="$(date -u +%Y-%m-%d_%H-%M-%S)"
  export LOG_TRACE_PATH="${LOG_TRACE_PATH:-${RUN_ROOT}/log/${ts}}"
  export WORKSPACE_PATH="${WORKSPACE_PATH:-${RUN_ROOT}/workspace}"
  mkdir -p "${LOG_TRACE_PATH}" "${WORKSPACE_PATH}"

  local args=(fin_quant --loop_n "${loop_n}")
  if [[ -n "${all_duration}" ]]; then
    args+=(--all_duration "${all_duration}")
  fi

  echo "LOG_TRACE_PATH=${LOG_TRACE_PATH}"
  echo "WORKSPACE_PATH=${WORKSPACE_PATH}"
  echo "Launching: onecli run --agent rdq-research -- rdagent ${args[*]}"
  exec onecli run --agent rdq-research -- "${RDAGENT}" "${args[@]}"
}

MODE="run"
LOOP_N="1"
ALL_DURATION=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) MODE="check"; shift ;;
    --loop_n)
      [[ $# -ge 2 ]] || fail "--loop_n needs a value"
      LOOP_N="$2"; shift 2 ;;
    --all_duration)
      [[ $# -ge 2 ]] || fail "--all_duration needs a value"
      ALL_DURATION="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *)
      usage >&2
      fail "unknown argument: $1"
      ;;
  esac
done

if [[ "${MODE}" == "check" ]]; then
  check_mode
else
  run_mode "${LOOP_N}" "${ALL_DURATION}"
fi
